import fs from "node:fs";
import path from "node:path";

export interface InitOptions {
  /** Project root (default: cwd) */
  path?: string;
  /** Overwrite if the workflow already exists */
  force?: boolean;
  /** Fail the job when risk is at least this level */
  failOn?: "high" | "medium" | "error";
  /** Output path relative to project root */
  output?: string;
  /** Pin deprisk-check version in the workflow */
  packageVersion?: string;
}

export interface InitResult {
  written: boolean;
  filePath: string;
  skipped?: boolean;
  message: string;
}

const DEFAULT_OUTPUT = ".github/workflows/deprisk.yml";

/**
 * Generate a GitHub Actions workflow that runs DepRisk on dependency PRs.
 */
export function generateWorkflowYaml(options: {
  failOn?: "high" | "medium" | "error";
  packageVersion?: string;
} = {}): string {
  const failOn = options.failOn ?? "high";
  const version = options.packageVersion ?? "0.8.0";

  return `# Generated by: deprisk init
# Runs DepRisk on PRs that change dependencies (Renovate / Dependabot / manual bumps).

name: DepRisk

on:
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"

permissions:
  contents: read
  pull-requests: write

jobs:
  deprisk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install DepRisk
        run: npm install -g deprisk-check@${version}

      - name: Prepare base lockfile
        run: |
          git fetch origin "\${{ github.base_ref }}" --depth=1 || true
          git show "origin/\${{ github.base_ref }}:package-lock.json" > /tmp/base-lock.json 2>/dev/null || true

      - name: Run DepRisk scan
        run: |
          if [ ! -f /tmp/base-lock.json ]; then
            echo "No base package-lock.json — skip."
            exit 0
          fi
          if [ ! -f package-lock.json ]; then
            echo "No package-lock.json in PR — skip."
            exit 0
          fi
          deprisk scan --path . --base-lock /tmp/base-lock.json --markdown --fail-on ${failOn}
`;
}

/**
 * Write `.github/workflows/deprisk.yml` into a project.
 */
export function initGitHubWorkflow(options: InitOptions = {}): InitResult {
  const projectDir = path.resolve(options.path ?? process.cwd());
  const relativeOut = options.output ?? DEFAULT_OUTPUT;
  const filePath = path.resolve(projectDir, relativeOut);

  if (fs.existsSync(filePath) && !options.force) {
    return {
      written: false,
      skipped: true,
      filePath,
      message:
        `Workflow already exists at ${relativeOut}. Re-run with --force to overwrite.`,
    };
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const yaml = generateWorkflowYaml({
    failOn: options.failOn,
    packageVersion: options.packageVersion,
  });
  fs.writeFileSync(filePath, yaml, "utf8");

  return {
    written: true,
    filePath,
    message: `Created ${relativeOut}`,
  };
}
